/**
 * Debate exhibit emoji catalog — searchable labels + keywords for evidence setup.
 * Keep entries concrete and debate-usable; prefer everyday objects and symbols.
 */

export interface DebateEvidenceEmojiCatalogEntry {
  emoji: string;
  label: string;
  keywords: readonly string[];
}

export const DEBATE_EVIDENCE_EMOJI_CATALOG: readonly DebateEvidenceEmojiCatalogEntry[] =
  [
    // Core exhibit / proof
    { emoji: "📦", label: "box", keywords: ["package", "container", "parcel", "carton"] },
    { emoji: "🧾", label: "receipt", keywords: ["invoice", "proof", "evidence", "bill", "stub"] },
    { emoji: "📜", label: "scroll", keywords: ["history", "law", "decree", "parchment", "document"] },
    { emoji: "📄", label: "document", keywords: ["paper", "file", "page", "report", "memo"] },
    { emoji: "📁", label: "folder", keywords: ["files", "dossier", "casefile"] },
    { emoji: "🗂️", label: "index cards", keywords: ["organize", "filing", "tabs"] },
    { emoji: "📝", label: "memo", keywords: ["note", "write", "notepad"] },
    { emoji: "🖊️", label: "pen", keywords: ["write", "ink", "signature"] },
    { emoji: "✏️", label: "pencil", keywords: ["write", "sketch", "graphite"] },
    { emoji: "✒️", label: "fountain pen", keywords: ["ink", "signature", "quill"] },
    { emoji: "✉️", label: "letter", keywords: ["mail", "envelope", "message", "correspondence"] },
    { emoji: "📧", label: "email", keywords: ["inbox", "message", "digital mail"] },
    { emoji: "📮", label: "mailbox", keywords: ["post", "mail", "delivery"] },
    { emoji: "📓", label: "notebook", keywords: ["diary", "journal", "notes", "log"] },
    { emoji: "📔", label: "journal", keywords: ["diary", "notebook", "memoir"] },
    { emoji: "📕", label: "book", keywords: ["novel", "text", "reading", "volume"] },
    { emoji: "📗", label: "green book", keywords: ["manual", "guide", "text"] },
    { emoji: "📘", label: "blue book", keywords: ["manual", "textbook", "study"] },
    { emoji: "📙", label: "orange book", keywords: ["manual", "reference"] },
    { emoji: "📚", label: "books", keywords: ["library", "stack", "study", "education"] },
    { emoji: "🔖", label: "bookmark", keywords: ["marker", "page", "tag"] },
    { emoji: "🏷️", label: "label", keywords: ["tag", "price", "sticker", "name tag"] },
    { emoji: "📎", label: "paperclip", keywords: ["clip", "attach", "office"] },
    { emoji: "🔗", label: "link", keywords: ["chain", "connection", "url", "hyperlink"] },
    { emoji: "📌", label: "pushpin", keywords: ["pin", "tack", "bulletin"] },
    { emoji: "📍", label: "pin", keywords: ["location", "map pin", "marker"] },
    { emoji: "✂️", label: "scissors", keywords: ["cut", "trim", "craft"] },
    { emoji: "🗃️", label: "card file", keywords: ["cabinet", "archive", "drawer"] },
    { emoji: "🗄️", label: "filing cabinet", keywords: ["archive", "records", "storage"] },

    // Keys, locks, security
    { emoji: "🔑", label: "key", keywords: ["access", "lock", "unlock", "password"] },
    { emoji: "🗝️", label: "old key", keywords: ["antique key", "skeleton key", "access"] },
    { emoji: "🔒", label: "lock", keywords: ["security", "privacy", "safe", "padlock"] },
    { emoji: "🔓", label: "unlocked", keywords: ["open lock", "access", "security"] },
    { emoji: "🛡️", label: "shield", keywords: ["protect", "defense", "guard", "safety"] },
    { emoji: "🔐", label: "locked with key", keywords: ["secure", "encrypted", "privacy"] },

    // Time
    { emoji: "⏰", label: "alarm clock", keywords: ["alarm", "time", "clock", "wake"] },
    { emoji: "🕰️", label: "mantel clock", keywords: ["clock", "time", "antique", "watch"] },
    { emoji: "⌚", label: "watch", keywords: ["wristwatch", "time", "clock"] },
    { emoji: "⏱️", label: "stopwatch", keywords: ["timer", "race", "seconds"] },
    { emoji: "⏲️", label: "timer", keywords: ["kitchen timer", "countdown"] },
    { emoji: "⌛", label: "hourglass done", keywords: ["sand", "time up", "deadline"] },
    { emoji: "⏳", label: "hourglass", keywords: ["sand", "waiting", "time", "deadline"] },
    { emoji: "📅", label: "calendar", keywords: ["date", "schedule", "day", "agenda"] },
    { emoji: "🗓️", label: "spiral calendar", keywords: ["date", "planner", "schedule"] },

    // Navigation / travel
    { emoji: "🧭", label: "compass", keywords: ["direction", "navigation", "north"] },
    { emoji: "🗺️", label: "map", keywords: ["route", "geography", "transit", "atlas"] },
    { emoji: "🔦", label: "flashlight", keywords: ["torch", "light", "beam"] },
    { emoji: "🏮", label: "lantern", keywords: ["lamp", "light", "festival lantern"] },
    { emoji: "💡", label: "light bulb", keywords: ["idea", "insight", "innovation", "light"] },
    { emoji: "🕯️", label: "candle", keywords: ["flame", "light", "wax", "vigil"] },
    { emoji: "🪔", label: "oil lamp", keywords: ["diya", "flame", "light"] },
    { emoji: "✈️", label: "airplane", keywords: ["plane", "flight", "travel", "aviation"] },
    { emoji: "🛫", label: "departure", keywords: ["takeoff", "airport", "flight"] },
    { emoji: "🛬", label: "arrival", keywords: ["landing", "airport", "flight"] },
    { emoji: "🚀", label: "rocket", keywords: ["space", "launch", "toy rocket", "missile"] },
    { emoji: "🛰️", label: "satellite", keywords: ["orbit", "space", "comms"] },
    { emoji: "🛸", label: "flying saucer", keywords: ["ufo", "alien", "spaceship"] },
    { emoji: "🚁", label: "helicopter", keywords: ["chopper", "aircraft"] },
    { emoji: "🚂", label: "train", keywords: ["locomotive", "rail", "steam", "freight", "transit", "transportation"] },
    { emoji: "🚆", label: "passenger train", keywords: ["rail", "transit", "transportation", "subway"] },
    { emoji: "🚇", label: "metro", keywords: ["subway", "underground", "transit"] },
    { emoji: "🚊", label: "tram", keywords: ["streetcar", "trolley", "transit"] },
    { emoji: "🚌", label: "bus", keywords: ["transit", "transportation", "coach"] },
    { emoji: "🚎", label: "trolleybus", keywords: ["bus", "transit"] },
    { emoji: "🚐", label: "minibus", keywords: ["van", "shuttle"] },
    { emoji: "🚑", label: "ambulance", keywords: ["emergency", "medical", "rescue"] },
    { emoji: "🚒", label: "fire engine", keywords: ["firefighter", "truck", "emergency"] },
    { emoji: "🚓", label: "police car", keywords: ["cop", "patrol", "law enforcement"] },
    { emoji: "🚕", label: "taxi", keywords: ["cab", "rideshare"] },
    { emoji: "🚗", label: "car", keywords: ["automobile", "vehicle", "drive", "transportation"] },
    { emoji: "🚙", label: "suv", keywords: ["car", "vehicle"] },
    { emoji: "🚚", label: "delivery truck", keywords: ["lorry", "shipping", "freight"] },
    { emoji: "🚲", label: "bicycle", keywords: ["bike", "cycle", "pedal"] },
    { emoji: "🛴", label: "scooter", keywords: ["kick scooter", "ride"] },
    { emoji: "🛵", label: "motor scooter", keywords: ["moped", "vespa"] },
    { emoji: "🏍️", label: "motorcycle", keywords: ["bike", "motorbike"] },
    { emoji: "🚢", label: "ship", keywords: ["boat", "vessel", "cruise", "maritime"] },
    { emoji: "⛴️", label: "ferry", keywords: ["boat", "crossing"] },
    { emoji: "⛵", label: "sailboat", keywords: ["yacht", "sailing", "boat"] },
    { emoji: "🛶", label: "canoe", keywords: ["kayak", "paddle", "boat"] },
    { emoji: "⚓", label: "anchor", keywords: ["navy", "harbor", "mooring"] },
    { emoji: "🧳", label: "luggage", keywords: ["suitcase", "baggage", "travel"] },
    { emoji: "🎒", label: "backpack", keywords: ["bag", "school", "hiking"] },
    { emoji: "👜", label: "handbag", keywords: ["purse", "bag", "clutch"] },
    { emoji: "💼", label: "briefcase", keywords: ["suitcase", "work bag", "office"] },
    { emoji: "👛", label: "wallet", keywords: ["purse", "money", "billfold"] },

    // Optics / media
    { emoji: "📷", label: "camera", keywords: ["photo", "photograph", "picture", "snapshot"] },
    { emoji: "📸", label: "flash camera", keywords: ["photo", "selfie", "snapshot"] },
    { emoji: "🎥", label: "movie camera", keywords: ["film", "video", "cinema"] },
    { emoji: "📹", label: "video camera", keywords: ["camcorder", "recording"] },
    { emoji: "🎞️", label: "film frames", keywords: ["cinema", "reel", "movie"] },
    { emoji: "📽️", label: "film projector", keywords: ["cinema", "screening"] },
    { emoji: "📺", label: "television", keywords: ["tv", "screen", "broadcast"] },
    { emoji: "📻", label: "radio", keywords: ["broadcast", "audio", "news", "am fm"] },
    { emoji: "📡", label: "satellite antenna", keywords: ["dish", "broadcast", "signal"] },
    { emoji: "🎤", label: "microphone", keywords: ["mic", "speech", "podcast", "voice"] },
    { emoji: "🎧", label: "headphones", keywords: ["earphones", "audio", "listen"] },
    { emoji: "🔊", label: "speaker", keywords: ["loud", "audio", "sound", "volume"] },
    { emoji: "📢", label: "loudspeaker", keywords: ["announce", "pa", "megaphone"] },
    { emoji: "📣", label: "megaphone", keywords: ["cheer", "announce", "whistle", "rally"] },
    { emoji: "🔔", label: "bell", keywords: ["ring", "alarm", "chime", "notification"] },
    { emoji: "🔕", label: "muted bell", keywords: ["silent", "mute", "quiet"] },
    { emoji: "💿", label: "cd", keywords: ["disc", "album", "music", "record"] },
    { emoji: "📀", label: "dvd", keywords: ["disc", "movie", "optical"] },
    { emoji: "💽", label: "minidisc", keywords: ["disc", "media"] },
    { emoji: "💾", label: "floppy disk", keywords: ["save", "storage", "disk"] },
    { emoji: "🖥️", label: "desktop computer", keywords: ["pc", "monitor", "workstation"] },
    { emoji: "💻", label: "laptop", keywords: ["computer", "technology", "software", "notebook"] },
    { emoji: "⌨️", label: "keyboard", keywords: ["type", "keys", "computer"] },
    { emoji: "🖱️", label: "computer mouse", keywords: ["click", "pointer"] },
    { emoji: "🖨️", label: "printer", keywords: ["print", "paper", "office"] },
    { emoji: "📱", label: "phone", keywords: ["mobile", "cellphone", "smartphone", "call"] },
    { emoji: "☎️", label: "telephone", keywords: ["call", "landline", "dial"] },
    { emoji: "📞", label: "receiver", keywords: ["call", "phone", "hotline"] },
    { emoji: "🔋", label: "battery", keywords: ["power", "charge", "energy"] },
    { emoji: "🔌", label: "plug", keywords: ["electric", "outlet", "power"] },
    { emoji: "🪞", label: "mirror", keywords: ["reflection", "glass", "looking glass"] },
    { emoji: "🪟", label: "window", keywords: ["pane", "view", "glass"] },
    { emoji: "🔎", label: "magnifying glass", keywords: ["search", "inspect", "investigate", "clue"] },
    { emoji: "🔍", label: "search", keywords: ["magnify", "find", "investigate"] },

    // Clothing / personal
    { emoji: "🧸", label: "teddy bear", keywords: ["toy", "plush", "childhood", "stuffed animal"] },
    { emoji: "🧤", label: "glove", keywords: ["glove", "hand", "mitten", "winter", "gloves"] },
    { emoji: "🥊", label: "boxing glove", keywords: ["glove", "punch", "sport", "fight", "boxing"] },
    { emoji: "✋", label: "hand", keywords: ["glove", "palm", "stop", "raise hand", "gesture"] },
    { emoji: "👋", label: "waving hand", keywords: ["hello", "goodbye", "wave"] },
    { emoji: "👍", label: "thumbs up", keywords: ["approve", "yes", "like", "agree"] },
    { emoji: "👎", label: "thumbs down", keywords: ["disapprove", "no", "reject"] },
    { emoji: "👏", label: "clapping hands", keywords: ["applause", "clap", "ovation", "celebrate"] },
    { emoji: "🙌", label: "raising hands", keywords: ["praise", "hooray", "yes", "celebrate"] },
    { emoji: "🤝", label: "handshake", keywords: ["deal", "agreement", "partnership", "truce"] },
    { emoji: "🙏", label: "folded hands", keywords: ["please", "thanks", "pray", "hope"] },
    { emoji: "💪", label: "flexed biceps", keywords: ["strength", "power", "strong", "muscle"] },
    { emoji: "👞", label: "shoe", keywords: ["oxford", "footwear", "boot", "dress shoe"] },
    { emoji: "👟", label: "sneaker", keywords: ["shoe", "trainer", "running", "footwear"] },
    { emoji: "🥾", label: "hiking boot", keywords: ["boot", "trail", "outdoor"] },
    { emoji: "👠", label: "high heel", keywords: ["shoe", "fashion", "pump"] },
    { emoji: "👡", label: "sandal", keywords: ["shoe", "summer", "flip flop"] },
    { emoji: "🎩", label: "top hat", keywords: ["hat", "formal", "magician"] },
    { emoji: "🧢", label: "cap", keywords: ["hat", "baseball", "clothing"] },
    { emoji: "👒", label: "sun hat", keywords: ["hat", "bonnet", "summer"] },
    { emoji: "🎓", label: "graduation cap", keywords: ["diploma", "graduate", "school", "education", "commencement"] },
    { emoji: "👑", label: "crown", keywords: ["king", "queen", "royalty", "monarch"] },
    { emoji: "💍", label: "ring", keywords: ["jewelry", "wedding", "engagement", "locket"] },
    { emoji: "💎", label: "gem stone", keywords: ["diamond", "jewel", "crystal", "precious"] },
    { emoji: "👓", label: "glasses", keywords: ["spectacles", "eyewear", "vision"] },
    { emoji: "🕶️", label: "sunglasses", keywords: ["shades", "cool", "eyewear"] },
    { emoji: "🥽", label: "goggles", keywords: ["safety", "swim", "lab"] },
    { emoji: "🧣", label: "scarf", keywords: ["neck", "winter", "wrap"] },
    { emoji: "👔", label: "necktie", keywords: ["tie", "formal", "office"] },
    { emoji: "👕", label: "t-shirt", keywords: ["shirt", "clothing", "tee"] },
    { emoji: "👖", label: "jeans", keywords: ["pants", "denim", "trousers"] },
    { emoji: "🧥", label: "coat", keywords: ["jacket", "outerwear"] },
    { emoji: "👗", label: "dress", keywords: ["gown", "clothing", "fashion"] },
    { emoji: "👘", label: "kimono", keywords: ["robe", "traditional", "clothing"] },
    { emoji: "🦺", label: "safety vest", keywords: ["high visibility", "construction", "worker"] },
    { emoji: "🪖", label: "military helmet", keywords: ["army", "soldier", "war"] },
    { emoji: "⛑️", label: "rescue helmet", keywords: ["safety", "first aid", "helmet"] },

    // Tools / household
    { emoji: "🔨", label: "hammer", keywords: ["tool", "build", "construction", "nail"] },
    { emoji: "⚒️", label: "hammer and pick", keywords: ["mining", "tools", "labor"] },
    { emoji: "🛠️", label: "tools", keywords: ["hammer wrench", "repair", "fix"] },
    { emoji: "🔧", label: "wrench", keywords: ["spanner", "tool", "repair", "crowbar", "pry"] },
    { emoji: "🪛", label: "screwdriver", keywords: ["tool", "screw", "fix"] },
    { emoji: "🔩", label: "nut and bolt", keywords: ["hardware", "fastener"] },
    { emoji: "⚙️", label: "gear", keywords: ["cog", "machinery", "settings", "industry"] },
    { emoji: "🧱", label: "brick", keywords: ["wall", "build", "masonry"] },
    { emoji: "🪜", label: "ladder", keywords: ["climb", "steps", "reach"] },
    { emoji: "🧲", label: "magnet", keywords: ["attract", "magnetic"] },
    { emoji: "🔫", label: "water pistol", keywords: ["gun", "toy gun", "squirt"] },
    { emoji: "🪓", label: "axe", keywords: ["hatchet", "chop", "wood"] },
    { emoji: "⛏️", label: "pick", keywords: ["mining", "dig", "pickaxe"] },
    { emoji: "🪚", label: "saw", keywords: ["woodcut", "carpenter"] },
    { emoji: "🔪", label: "knife", keywords: ["blade", "kitchen", "cut"] },
    { emoji: "🗡️", label: "dagger", keywords: ["sword", "blade", "weapon"] },
    { emoji: "⚔️", label: "crossed swords", keywords: ["duel", "battle", "conflict"] },
    { emoji: "🏹", label: "bow and arrow", keywords: ["archery", "hunt"] },
    { emoji: "💣", label: "bomb", keywords: ["explosive", "danger", "blast"] },
    { emoji: "🧨", label: "firecracker", keywords: ["dynamite", "explosive", "firework", "celebrate"] },
    { emoji: "🪢", label: "knot", keywords: ["rope", "cord", "tie"] },
    { emoji: "🧵", label: "thread", keywords: ["sewing", "spool", "string"] },
    { emoji: "🧶", label: "yarn", keywords: ["knit", "wool", "craft"] },
    { emoji: "🪡", label: "needle", keywords: ["sew", "stitch", "tailor"] },
    { emoji: "🧹", label: "broom", keywords: ["sweep", "clean", "witch"] },
    { emoji: "🧺", label: "basket", keywords: ["hamper", "wicker", "laundry"] },
    { emoji: "🧻", label: "roll of paper", keywords: ["toilet paper", "tissue"] },
    { emoji: "🧼", label: "soap", keywords: ["clean", "wash", "hygiene"] },
    { emoji: "🪥", label: "toothbrush", keywords: ["dental", "brush", "hygiene"] },
    { emoji: "🧽", label: "sponge", keywords: ["clean", "wash", "absorb"] },
    { emoji: "🧯", label: "fire extinguisher", keywords: ["safety", "fire", "emergency"] },
    { emoji: "🛒", label: "shopping cart", keywords: ["basket", "retail", "grocery"] },
    { emoji: "🛎️", label: "bellhop bell", keywords: ["service", "hotel", "ring"] },
    { emoji: "🚪", label: "door", keywords: ["entrance", "exit", "portal"] },
    { emoji: "🪑", label: "chair", keywords: ["seat", "furniture"] },
    { emoji: "🛏️", label: "bed", keywords: ["sleep", "mattress", "rest"] },
    { emoji: "🛋️", label: "couch", keywords: ["sofa", "lounge", "furniture"] },
    { emoji: "🚽", label: "toilet", keywords: ["bathroom", "restroom"] },
    { emoji: "🚿", label: "shower", keywords: ["bath", "water", "clean"] },
    { emoji: "🛁", label: "bathtub", keywords: ["bath", "soak"] },
    { emoji: "🧴", label: "lotion bottle", keywords: ["moisturizer", "soap bottle"] },

    // Kitchen / utensils
    { emoji: "🥄", label: "spoon", keywords: ["utensil", "silverware", "cutlery"] },
    { emoji: "🍴", label: "fork and knife", keywords: ["utensil", "dining", "cutlery", "eat"] },
    { emoji: "🥢", label: "chopsticks", keywords: ["utensil", "asian dining"] },
    { emoji: "🍽️", label: "plate", keywords: ["dining", "place setting", "meal"] },
    { emoji: "🥣", label: "bowl", keywords: ["cereal", "soup", "dish"] },
    { emoji: "🥤", label: "cup with straw", keywords: ["drink", "soda", "beverage"] },
    { emoji: "☕", label: "coffee", keywords: ["mug", "tea", "cafe", "hot drink", "teacup"] },
    { emoji: "🫖", label: "teapot", keywords: ["tea", "brew", "kettle"] },
    { emoji: "🍵", label: "tea", keywords: ["green tea", "cup", "matcha"] },
    { emoji: "🍶", label: "sake", keywords: ["bottle", "japan", "rice wine"] },
    { emoji: "🍾", label: "champagne", keywords: ["bottle", "celebrate", "toast", "sparkling", "party", "celebration"] },
    { emoji: "🍷", label: "wine glass", keywords: ["wine", "drink", "toast", "celebrate"] },
    { emoji: "🍸", label: "cocktail", keywords: ["martini", "drink", "bar", "celebrate"] },
    { emoji: "🍹", label: "tropical drink", keywords: ["cocktail", "vacation", "party"] },
    { emoji: "🍺", label: "beer mug", keywords: ["beer", "pint", "pub", "celebrate"] },
    { emoji: "🍻", label: "clinking beers", keywords: ["cheers", "toast", "celebrate", "party", "celebration"] },
    { emoji: "🥂", label: "clinking glasses", keywords: ["toast", "champagne", "celebrate", "cheers", "celebration", "party"] },
    { emoji: "🥃", label: "tumbler glass", keywords: ["whiskey", "drink", "rocks glass"] },
    { emoji: "🧊", label: "ice cube", keywords: ["cold", "frozen", "chill"] },
    { emoji: "🥛", label: "milk glass", keywords: ["dairy", "drink"] },
    { emoji: "🍼", label: "baby bottle", keywords: ["infant", "milk", "feeding"] },

    // Celebration / party (the missing set for "Celebrate")
    { emoji: "🎉", label: "party popper", keywords: ["celebrate", "celebration", "party", "confetti", "congrats", "festive", "cheer"] },
    { emoji: "🎊", label: "confetti ball", keywords: ["celebration", "celebrate", "party", "confetti", "festive"] },
    { emoji: "🥳", label: "partying face", keywords: ["party", "celebrate", "celebration", "festive", "happy"] },
    { emoji: "🎈", label: "balloon", keywords: ["party", "celebrate", "celebration", "birthday", "helium"] },
    { emoji: "🎂", label: "birthday cake", keywords: ["birthday", "celebrate", "celebration", "party", "cake", "candles"] },
    { emoji: "🍰", label: "shortcake", keywords: ["cake", "dessert", "slice", "celebrate"] },
    { emoji: "🧁", label: "cupcake", keywords: ["cake", "frosting", "party", "dessert"] },
    { emoji: "🪅", label: "pinata", keywords: ["party", "celebrate", "candy", "festive"] },
    { emoji: "🎀", label: "ribbon", keywords: ["bow", "gift", "decorate", "celebrate"] },
    { emoji: "🎁", label: "wrapped gift", keywords: ["present", "gift", "celebrate", "birthday", "box"] },
    { emoji: "🎄", label: "christmas tree", keywords: ["holiday", "festive", "celebrate", "pine"] },
    { emoji: "🎆", label: "fireworks", keywords: ["celebrate", "celebration", "party", "skyburst", "new year", "festive"] },
    { emoji: "🎇", label: "sparkler", keywords: ["celebrate", "firework", "glow", "party"] },
    { emoji: "✨", label: "sparkles", keywords: ["shine", "magic", "celebrate", "glitter"] },
    { emoji: "⭐", label: "star", keywords: ["favorite", "rating", "night"] },
    { emoji: "🌟", label: "glowing star", keywords: ["shine", "celebrate", "success"] },
    { emoji: "💫", label: "dizzy", keywords: ["sparkle", "stars", "spin"] },
    { emoji: "🏆", label: "trophy", keywords: ["award", "win", "champion", "prize", "celebrate", "victory"] },
    { emoji: "🥇", label: "gold medal", keywords: ["first", "winner", "prize", "award", "celebrate"] },
    { emoji: "🥈", label: "silver medal", keywords: ["second", "prize", "award"] },
    { emoji: "🥉", label: "bronze medal", keywords: ["third", "prize", "award"] },
    { emoji: "🏅", label: "medal", keywords: ["award", "prize", "honor", "sports"] },
    { emoji: "🎖️", label: "military medal", keywords: ["honor", "award", "service"] },
    { emoji: "🏵️", label: "rosette", keywords: ["award", "ribbon", "prize"] },
    { emoji: "🎫", label: "ticket", keywords: ["admission", "pass", "stub", "event"] },
    { emoji: "🎟️", label: "admission tickets", keywords: ["event", "concert", "pass", "celebrate"] },

    // Food
    { emoji: "🍎", label: "apple", keywords: ["fruit", "food", "red apple"] },
    { emoji: "🍏", label: "green apple", keywords: ["fruit", "food"] },
    { emoji: "🍐", label: "pear", keywords: ["fruit", "food"] },
    { emoji: "🍊", label: "orange", keywords: ["fruit", "citrus", "tangerine"] },
    { emoji: "🍋", label: "lemon", keywords: ["citrus", "sour", "fruit"] },
    { emoji: "🍌", label: "banana", keywords: ["fruit", "food"] },
    { emoji: "🍉", label: "watermelon", keywords: ["fruit", "summer"] },
    { emoji: "🍇", label: "grapes", keywords: ["fruit", "vine", "wine"] },
    { emoji: "🍓", label: "strawberry", keywords: ["fruit", "berry"] },
    { emoji: "🫐", label: "blueberries", keywords: ["fruit", "berry"] },
    { emoji: "🍒", label: "cherries", keywords: ["fruit", "berry"] },
    { emoji: "🍑", label: "peach", keywords: ["fruit", "food"] },
    { emoji: "🥭", label: "mango", keywords: ["fruit", "tropical"] },
    { emoji: "🍍", label: "pineapple", keywords: ["fruit", "tropical"] },
    { emoji: "🥥", label: "coconut", keywords: ["fruit", "tropical"] },
    { emoji: "🥝", label: "kiwi", keywords: ["fruit", "food"] },
    { emoji: "🍅", label: "tomato", keywords: ["vegetable", "food", "sauce"] },
    { emoji: "🥑", label: "avocado", keywords: ["fruit", "food", "guacamole"] },
    { emoji: "🍆", label: "eggplant", keywords: ["vegetable", "aubergine"] },
    { emoji: "🥔", label: "potato", keywords: ["vegetable", "food", "spud"] },
    { emoji: "🥕", label: "carrot", keywords: ["vegetable", "food"] },
    { emoji: "🌽", label: "corn", keywords: ["vegetable", "maize", "food"] },
    { emoji: "🌶️", label: "hot pepper", keywords: ["chili", "spicy", "food"] },
    { emoji: "🫑", label: "bell pepper", keywords: ["vegetable", "capsicum"] },
    { emoji: "🥒", label: "cucumber", keywords: ["vegetable", "pickle"] },
    { emoji: "🥬", label: "leafy green", keywords: ["lettuce", "salad", "kale"] },
    { emoji: "🥦", label: "broccoli", keywords: ["vegetable", "food"] },
    { emoji: "🧄", label: "garlic", keywords: ["ingredient", "food"] },
    { emoji: "🧅", label: "onion", keywords: ["vegetable", "food"] },
    { emoji: "🍄", label: "mushroom", keywords: ["fungus", "food"] },
    { emoji: "🥜", label: "peanuts", keywords: ["nuts", "snack"] },
    { emoji: "🌰", label: "chestnut", keywords: ["nut", "autumn"] },
    { emoji: "🍞", label: "bread", keywords: ["loaf", "bakery", "food"] },
    { emoji: "🥐", label: "croissant", keywords: ["pastry", "bakery"] },
    { emoji: "🥖", label: "baguette", keywords: ["bread", "french"] },
    { emoji: "🥨", label: "pretzel", keywords: ["snack", "bakery"] },
    { emoji: "🧀", label: "cheese", keywords: ["dairy", "food", "wedge"] },
    { emoji: "🥚", label: "egg", keywords: ["food", "breakfast"] },
    { emoji: "🍳", label: "cooking", keywords: ["fried egg", "pan", "breakfast"] },
    { emoji: "🥞", label: "pancakes", keywords: ["breakfast", "food"] },
    { emoji: "🧇", label: "waffle", keywords: ["breakfast", "food"] },
    { emoji: "🥓", label: "bacon", keywords: ["meat", "breakfast"] },
    { emoji: "🥩", label: "cut of meat", keywords: ["steak", "beef", "food"] },
    { emoji: "🍗", label: "poultry leg", keywords: ["chicken", "meat", "food"] },
    { emoji: "🍖", label: "meat on bone", keywords: ["food", "bbq"] },
    { emoji: "🌭", label: "hot dog", keywords: ["food", "sausage"] },
    { emoji: "🍔", label: "hamburger", keywords: ["burger", "food", "fast food"] },
    { emoji: "🍟", label: "fries", keywords: ["chips", "fast food"] },
    { emoji: "🍕", label: "pizza", keywords: ["food", "slice", "italian"] },
    { emoji: "🥪", label: "sandwich", keywords: ["food", "lunch"] },
    { emoji: "🌮", label: "taco", keywords: ["food", "mexican"] },
    { emoji: "🌯", label: "burrito", keywords: ["food", "wrap"] },
    { emoji: "🥙", label: "stuffed flatbread", keywords: ["falafel", "gyro", "food"] },
    { emoji: "🧆", label: "falafel", keywords: ["food", "chickpea"] },
    { emoji: "🍝", label: "spaghetti", keywords: ["pasta", "noodles", "italian"] },
    { emoji: "🍜", label: "steaming bowl", keywords: ["ramen", "noodles", "soup"] },
    { emoji: "🍲", label: "pot of food", keywords: ["stew", "soup", "meal"] },
    { emoji: "🍛", label: "curry", keywords: ["rice", "food", "spice"] },
    { emoji: "🍣", label: "sushi", keywords: ["japanese", "fish", "food"] },
    { emoji: "🍱", label: "bento", keywords: ["lunch box", "japanese", "food"] },
    { emoji: "🥟", label: "dumpling", keywords: ["gyoza", "food"] },
    { emoji: "🦪", label: "oyster", keywords: ["shellfish", "seafood"] },
    { emoji: "🦐", label: "shrimp", keywords: ["seafood", "prawn"] },
    { emoji: "🦞", label: "lobster", keywords: ["seafood", "food"] },
    { emoji: "🦀", label: "crab", keywords: ["seafood", "food"] },
    { emoji: "🐟", label: "fish", keywords: ["seafood", "animal", "catch"] },
    { emoji: "🍦", label: "soft ice cream", keywords: ["dessert", "cone", "sweet"] },
    { emoji: "🍨", label: "ice cream", keywords: ["dessert", "sweet", "scoop"] },
    { emoji: "🍩", label: "doughnut", keywords: ["donut", "dessert", "sweet"] },
    { emoji: "🍪", label: "cookie", keywords: ["biscuit", "dessert", "sweet"] },
    { emoji: "🍫", label: "chocolate", keywords: ["candy", "bar", "sweet"] },
    { emoji: "🍬", label: "candy", keywords: ["sweet", "wrapper"] },
    { emoji: "🍭", label: "lollipop", keywords: ["candy", "sweet"] },
    { emoji: "🍮", label: "custard", keywords: ["pudding", "dessert"] },
    { emoji: "🍯", label: "honey pot", keywords: ["sweet", "bee", "jar"] },
    { emoji: "🧂", label: "salt", keywords: ["seasoning", "shaker"] },

    // Nature
    { emoji: "🌱", label: "seedling", keywords: ["plant", "growth", "sprout", "nature", "environment"] },
    { emoji: "🌿", label: "herb", keywords: ["leaf", "plant", "nature", "green"] },
    { emoji: "☘️", label: "shamrock", keywords: ["clover", "luck", "irish", "plant"] },
    { emoji: "🍀", label: "four leaf clover", keywords: ["luck", "lucky", "plant"] },
    { emoji: "🌵", label: "cactus", keywords: ["desert", "plant", "succulent"] },
    { emoji: "🌴", label: "palm tree", keywords: ["tropical", "beach", "tree"] },
    { emoji: "🌳", label: "deciduous tree", keywords: ["tree", "forest", "nature"] },
    { emoji: "🌲", label: "evergreen tree", keywords: ["pine", "forest", "christmas"] },
    { emoji: "🍂", label: "fallen leaf", keywords: ["autumn", "fall", "leaf"] },
    { emoji: "🍁", label: "maple leaf", keywords: ["canada", "autumn", "leaf"] },
    { emoji: "🌺", label: "hibiscus", keywords: ["flower", "tropical"] },
    { emoji: "🌻", label: "sunflower", keywords: ["flower", "yellow"] },
    { emoji: "🌹", label: "rose", keywords: ["flower", "love", "romance"] },
    { emoji: "🌷", label: "tulip", keywords: ["flower", "spring"] },
    { emoji: "🌸", label: "cherry blossom", keywords: ["flower", "sakura", "spring"] },
    { emoji: "💐", label: "bouquet", keywords: ["flowers", "gift", "celebrate"] },
    { emoji: "🌾", label: "sheaf of rice", keywords: ["grain", "farm", "harvest"] },
    { emoji: "🌎", label: "earth americas", keywords: ["world", "planet", "globe", "climate"] },
    { emoji: "🌍", label: "earth africa", keywords: ["world", "planet", "globe"] },
    { emoji: "🌏", label: "earth asia", keywords: ["world", "planet", "globe"] },
    { emoji: "🌐", label: "globe meridians", keywords: ["internet", "world", "web"] },
    { emoji: "🌑", label: "new moon", keywords: ["night", "lunar", "dark"] },
    { emoji: "🌕", label: "full moon", keywords: ["night", "lunar"] },
    { emoji: "🌙", label: "crescent moon", keywords: ["night", "lunar", "sleep"] },
    { emoji: "☀️", label: "sun", keywords: ["sunny", "day", "weather", "solar"] },
    { emoji: "🌤️", label: "sun behind cloud", keywords: ["partly cloudy", "weather"] },
    { emoji: "⛅", label: "sun behind cloud", keywords: ["cloudy", "weather"] },
    { emoji: "☁️", label: "cloud", keywords: ["weather", "sky", "overcast"] },
    { emoji: "🌧️", label: "cloud with rain", keywords: ["rain", "weather", "storm"] },
    { emoji: "⛈️", label: "cloud with lightning", keywords: ["storm", "thunder", "weather"] },
    { emoji: "🌩️", label: "lightning", keywords: ["storm", "electric", "weather"] },
    { emoji: "❄️", label: "snowflake", keywords: ["snow", "cold", "winter", "ice"] },
    { emoji: "☃️", label: "snowman", keywords: ["winter", "snow", "cold"] },
    { emoji: "🌪️", label: "tornado", keywords: ["twister", "storm", "wind"] },
    { emoji: "🌫️", label: "fog", keywords: ["mist", "haze", "weather"] },
    { emoji: "🌈", label: "rainbow", keywords: ["pride", "weather", "hope", "colors"] },
    { emoji: "🔥", label: "fire", keywords: ["flame", "burn", "hot", "matchbook"] },
    { emoji: "💧", label: "droplet", keywords: ["water", "drop", "tear"] },
    { emoji: "💦", label: "sweat droplets", keywords: ["water", "splash", "wet"] },
    { emoji: "🌊", label: "water wave", keywords: ["ocean", "sea", "surf"] },
    { emoji: "⛰️", label: "mountain", keywords: ["peak", "hike", "nature"] },
    { emoji: "🏔️", label: "snow capped mountain", keywords: ["alps", "peak"] },
    { emoji: "🌋", label: "volcano", keywords: ["eruption", "lava", "mountain"] },
    { emoji: "🏖️", label: "beach", keywords: ["umbrella", "sand", "vacation"] },
    { emoji: "🏝️", label: "desert island", keywords: ["tropical", "alone", "beach"] },
    { emoji: "🏜️", label: "desert", keywords: ["sand", "dunes", "arid"] },
    { emoji: "🏕️", label: "camping", keywords: ["tent", "outdoors"] },
    { emoji: "⛺", label: "tent", keywords: ["camping", "shelter"] },
    { emoji: "🏠", label: "house", keywords: ["home", "housing", "property", "building"] },
    { emoji: "🏡", label: "house with garden", keywords: ["home", "suburb"] },
    { emoji: "🏢", label: "office building", keywords: ["work", "skyscraper", "corporate"] },
    { emoji: "🏛️", label: "classical building", keywords: ["institution", "government", "court", "museum", "capitol"] },
    { emoji: "🏟️", label: "stadium", keywords: ["arena", "sports", "crowd"] },
    { emoji: "🏗️", label: "construction", keywords: ["crane", "building", "site"] },
    { emoji: "🏭", label: "factory", keywords: ["industry", "plant", "smokestack"] },
    { emoji: "🏪", label: "convenience store", keywords: ["shop", "retail"] },
    { emoji: "🏫", label: "school", keywords: ["education", "classroom", "campus"] },
    { emoji: "🏥", label: "hospital", keywords: ["medical", "clinic", "health"] },
    { emoji: "🏦", label: "bank", keywords: ["finance", "money", "institution"] },
    { emoji: "🏨", label: "hotel", keywords: ["lodging", "inn"] },
    { emoji: "⛪", label: "church", keywords: ["religion", "worship", "chapel"] },
    { emoji: "🕌", label: "mosque", keywords: ["religion", "islam", "worship"] },
    { emoji: "🕍", label: "synagogue", keywords: ["religion", "jewish", "worship"] },
    { emoji: "🛕", label: "hindu temple", keywords: ["religion", "worship"] },
    { emoji: "🗼", label: "tokyo tower", keywords: ["landmark", "tower"] },
    { emoji: "🗽", label: "statue of liberty", keywords: ["freedom", "america", "landmark"] },
    { emoji: "🗿", label: "moai", keywords: ["statue", "stone", "easter island"] },

    // Animals
    { emoji: "🐶", label: "dog face", keywords: ["puppy", "pet", "animal", "dog"] },
    { emoji: "🐕", label: "dog", keywords: ["pet", "animal", "canine"] },
    { emoji: "🦮", label: "guide dog", keywords: ["service", "blind", "assistance"] },
    { emoji: "🐈", label: "cat", keywords: ["pet", "animal", "feline"] },
    { emoji: "🐱", label: "cat face", keywords: ["kitten", "pet", "animal"] },
    { emoji: "🦁", label: "lion", keywords: ["animal", "cat", "king"] },
    { emoji: "🐯", label: "tiger face", keywords: ["animal", "big cat"] },
    { emoji: "🐻", label: "bear", keywords: ["animal", "wildlife"] },
    { emoji: "🐼", label: "panda", keywords: ["animal", "bear"] },
    { emoji: "🐨", label: "koala", keywords: ["animal", "australia"] },
    { emoji: "🐵", label: "monkey face", keywords: ["animal", "primate"] },
    { emoji: "🐒", label: "monkey", keywords: ["animal", "primate"] },
    { emoji: "🦍", label: "gorilla", keywords: ["ape", "animal", "primate"] },
    { emoji: "🦧", label: "orangutan", keywords: ["ape", "animal", "primate"] },
    { emoji: "🦊", label: "fox", keywords: ["animal", "wildlife"] },
    { emoji: "🐺", label: "wolf", keywords: ["animal", "wildlife"] },
    { emoji: "🦄", label: "unicorn", keywords: ["mythical", "horse", "magic"] },
    { emoji: "🐴", label: "horse face", keywords: ["animal", "equine"] },
    { emoji: "🦓", label: "zebra", keywords: ["animal", "stripes"] },
    { emoji: "🦌", label: "deer", keywords: ["animal", "stag", "wildlife"] },
    { emoji: "🐮", label: "cow face", keywords: ["cattle", "animal", "farm"] },
    { emoji: "🐷", label: "pig face", keywords: ["animal", "farm"] },
    { emoji: "🐽", label: "pig nose", keywords: ["snout", "animal"] },
    { emoji: "🐏", label: "ram", keywords: ["sheep", "animal"] },
    { emoji: "🐑", label: "ewe", keywords: ["sheep", "animal", "farm"] },
    { emoji: "🐐", label: "goat", keywords: ["animal", "farm"] },
    { emoji: "🐪", label: "camel", keywords: ["desert", "animal"] },
    { emoji: "🦒", label: "giraffe", keywords: ["animal", "tall"] },
    { emoji: "🐘", label: "elephant", keywords: ["animal", "wildlife"] },
    { emoji: "🦏", label: "rhinoceros", keywords: ["animal", "wildlife"] },
    { emoji: "🦛", label: "hippopotamus", keywords: ["animal", "wildlife"] },
    { emoji: "🐁", label: "mouse", keywords: ["rodent", "animal"] },
    { emoji: "🐀", label: "rat", keywords: ["rodent", "animal"] },
    { emoji: "🐇", label: "rabbit", keywords: ["bunny", "animal"] },
    { emoji: "🐿️", label: "chipmunk", keywords: ["squirrel", "animal"] },
    { emoji: "🦔", label: "hedgehog", keywords: ["animal", "spines"] },
    { emoji: "🦇", label: "bat", keywords: ["animal", "night"] },
    { emoji: "🐻‍❄️", label: "polar bear", keywords: ["arctic", "animal"] },
    { emoji: "🦃", label: "turkey", keywords: ["bird", "thanksgiving"] },
    { emoji: "🐔", label: "chicken", keywords: ["bird", "farm", "hen"] },
    { emoji: "🐓", label: "rooster", keywords: ["bird", "farm"] },
    { emoji: "🐣", label: "hatching chick", keywords: ["bird", "baby", "egg"] },
    { emoji: "🐦", label: "bird", keywords: ["animal", "avian", "paper crane", "origami"] },
    { emoji: "🐧", label: "penguin", keywords: ["bird", "antarctic"] },
    { emoji: "🕊️", label: "dove", keywords: ["peace", "bird", "olive"] },
    { emoji: "🦅", label: "eagle", keywords: ["bird", "raptor"] },
    { emoji: "🦆", label: "duck", keywords: ["bird", "waterfowl"] },
    { emoji: "🦉", label: "owl", keywords: ["bird", "wisdom", "night"] },
    { emoji: "🦚", label: "peacock", keywords: ["bird", "feathers"] },
    { emoji: "🦜", label: "parrot", keywords: ["bird", "tropical"] },
    { emoji: "🦢", label: "swan", keywords: ["bird", "elegant"] },
    { emoji: "🦩", label: "flamingo", keywords: ["bird", "pink"] },
    { emoji: "🪶", label: "feather", keywords: ["bird", "quill", "plume"] },
    { emoji: "🐸", label: "frog", keywords: ["amphibian", "animal"] },
    { emoji: "🐊", label: "crocodile", keywords: ["reptile", "alligator"] },
    { emoji: "🐢", label: "turtle", keywords: ["reptile", "tortoise"] },
    { emoji: "🦎", label: "lizard", keywords: ["reptile", "gecko"] },
    { emoji: "🐍", label: "snake", keywords: ["reptile", "serpent"] },
    { emoji: "🐲", label: "dragon face", keywords: ["mythical", "dragon"] },
    { emoji: "🐉", label: "dragon", keywords: ["mythical", "fantasy"] },
    { emoji: "🦕", label: "sauropod", keywords: ["dinosaur", "prehistoric"] },
    { emoji: "🦖", label: "t-rex", keywords: ["dinosaur", "prehistoric"] },
    { emoji: "🐳", label: "spouting whale", keywords: ["ocean", "mammal"] },
    { emoji: "🐋", label: "whale", keywords: ["ocean", "mammal"] },
    { emoji: "🐬", label: "dolphin", keywords: ["ocean", "mammal"] },
    { emoji: "🦭", label: "seal", keywords: ["ocean", "mammal"] },
    { emoji: "🦈", label: "shark", keywords: ["ocean", "fish"] },
    { emoji: "🐙", label: "octopus", keywords: ["ocean", "cephalopod"] },
    { emoji: "🦑", label: "squid", keywords: ["ocean", "cephalopod"] },
    { emoji: "🐚", label: "spiral shell", keywords: ["beach", "seashell"] },
    { emoji: "🐌", label: "snail", keywords: ["slow", "mollusk"] },
    { emoji: "🦋", label: "butterfly", keywords: ["insect", "wings"] },
    { emoji: "🐛", label: "bug", keywords: ["insect", "caterpillar"] },
    { emoji: "🐜", label: "ant", keywords: ["insect", "colony"] },
    { emoji: "🐝", label: "honeybee", keywords: ["insect", "pollinate", "honey"] },
    { emoji: "🪲", label: "beetle", keywords: ["insect", "bug"] },
    { emoji: "🐞", label: "lady beetle", keywords: ["ladybug", "insect"] },
    { emoji: "🦗", label: "cricket", keywords: ["insect", "chirp"] },
    { emoji: "🕷️", label: "spider", keywords: ["arachnid", "web"] },
    { emoji: "🕸️", label: "spider web", keywords: ["web", "trap"] },
    { emoji: "🦂", label: "scorpion", keywords: ["arachnid", "sting"] },

    // Health / science / law / debate
    { emoji: "🧠", label: "brain", keywords: ["mind", "psychology", "thought", "intelligence"] },
    { emoji: "🫀", label: "heart organ", keywords: ["anatomy", "health", "cardio"] },
    { emoji: "🫁", label: "lungs", keywords: ["anatomy", "breath", "health"] },
    { emoji: "🦷", label: "tooth", keywords: ["dental", "smile"] },
    { emoji: "🦴", label: "bone", keywords: ["skeleton", "anatomy"] },
    { emoji: "👀", label: "eyes", keywords: ["see", "watch", "look"] },
    { emoji: "👁️", label: "eye", keywords: ["vision", "see", "observe"] },
    { emoji: "👅", label: "tongue", keywords: ["taste", "speak"] },
    { emoji: "👄", label: "mouth", keywords: ["lips", "speak"] },
    { emoji: "🩺", label: "stethoscope", keywords: ["medicine", "doctor", "health", "medical", "clinic"] },
    { emoji: "💉", label: "syringe", keywords: ["vaccine", "shot", "medicine", "needle"] },
    { emoji: "💊", label: "pill", keywords: ["medicine", "drug", "capsule", "pharmacy"] },
    { emoji: "🩹", label: "bandage", keywords: ["band-aid", "first aid", "wound"] },
    { emoji: "🩸", label: "drop of blood", keywords: ["bleed", "health", "donation"] },
    { emoji: "🧬", label: "dna", keywords: ["genetics", "science", "helix"] },
    { emoji: "🦠", label: "microbe", keywords: ["virus", "bacteria", "germ"] },
    { emoji: "🧫", label: "petri dish", keywords: ["lab", "culture", "science"] },
    { emoji: "🧪", label: "test tube", keywords: ["chemistry", "experiment", "science", "lab"] },
    { emoji: "🔬", label: "microscope", keywords: ["science", "research", "lab", "inspect"] },
    { emoji: "🔭", label: "telescope", keywords: ["astronomy", "stars", "observe"] },
    { emoji: "📡", label: "satellite dish", keywords: ["antenna", "signal", "broadcast"] },
    { emoji: "⚖️", label: "balance scale", keywords: ["law", "justice", "court", "scales", "fairness"] },
    { emoji: "🧑‍⚖️", label: "judge", keywords: ["court", "law", "magistrate"] },
    { emoji: "👮", label: "police officer", keywords: ["cop", "law enforcement"] },
    { emoji: "🕵️", label: "detective", keywords: ["investigate", "spy", "clue"] },
    { emoji: "🪖", label: "helmet", keywords: ["military", "army"] },
    { emoji: "🔫", label: "pistol", keywords: ["gun", "weapon"] },
    { emoji: "🚨", label: "police car light", keywords: ["siren", "alert", "emergency"] },
    { emoji: "⚠️", label: "warning", keywords: ["caution", "danger", "risk", "alert"] },
    { emoji: "🚫", label: "prohibited", keywords: ["forbidden", "no", "ban", "stop"] },
    { emoji: "❌", label: "cross mark", keywords: ["no", "wrong", "error", "reject"] },
    { emoji: "✅", label: "check mark button", keywords: ["yes", "done", "approve", "ok"] },
    { emoji: "✔️", label: "check mark", keywords: ["yes", "correct", "approve"] },
    { emoji: "❓", label: "question", keywords: ["ask", "unknown", "help"] },
    { emoji: "❗", label: "exclamation", keywords: ["important", "alert", "emphasis"] },
    { emoji: "💬", label: "speech balloon", keywords: ["talk", "chat", "comment", "quote"] },
    { emoji: "💭", label: "thought balloon", keywords: ["think", "idea", "dream"] },
    { emoji: "🗯️", label: "anger balloon", keywords: ["shout", "comic", "rage"] },
    { emoji: "📢", label: "public address", keywords: ["announce", "loudspeaker"] },

    // Emotions / faces useful as symbols
    { emoji: "😀", label: "grinning face", keywords: ["happy", "smile", "joy"] },
    { emoji: "😂", label: "tears of joy", keywords: ["laugh", "funny", "lol"] },
    { emoji: "😊", label: "smiling face", keywords: ["happy", "blush", "kind"] },
    { emoji: "😍", label: "heart eyes", keywords: ["love", "adore", "crush"] },
    { emoji: "🤔", label: "thinking face", keywords: ["hmm", "consider", "ponder", "debate"] },
    { emoji: "😐", label: "neutral face", keywords: ["meh", "blank", "poker"] },
    { emoji: "😴", label: "sleeping face", keywords: ["tired", "sleep", "zzz"] },
    { emoji: "😢", label: "crying face", keywords: ["sad", "tear", "upset"] },
    { emoji: "😠", label: "angry face", keywords: ["mad", "anger", "upset"] },
    { emoji: "🤯", label: "exploding head", keywords: ["mind blown", "shock", "wow"] },
    { emoji: "😎", label: "smiling sunglasses", keywords: ["cool", "confident"] },
    { emoji: "🤖", label: "robot", keywords: ["ai", "bot", "android", "machine"] },
    { emoji: "👻", label: "ghost", keywords: ["spooky", "halloween", "spirit"] },
    { emoji: "💀", label: "skull", keywords: ["death", "danger", "bones"] },
    { emoji: "☠️", label: "skull and crossbones", keywords: ["poison", "danger", "pirate"] },
    { emoji: "👽", label: "alien", keywords: ["ufo", "extraterrestrial"] },
    { emoji: "💩", label: "pile of poo", keywords: ["poop", "mess", "joke"] },
    { emoji: "🙈", label: "see-no-evil", keywords: ["monkey", "hide", "embarrassed"] },
    { emoji: "🙉", label: "hear-no-evil", keywords: ["monkey", "deaf"] },
    { emoji: "🙊", label: "speak-no-evil", keywords: ["monkey", "silent", "secret"] },

    // Sports / games
    { emoji: "⚽", label: "soccer ball", keywords: ["football", "sport", "ball"] },
    { emoji: "🏀", label: "basketball", keywords: ["sport", "ball", "hoop"] },
    { emoji: "🏈", label: "american football", keywords: ["sport", "ball", "nfl"] },
    { emoji: "⚾", label: "baseball", keywords: ["sport", "ball"] },
    { emoji: "🎾", label: "tennis", keywords: ["sport", "ball", "racket"] },
    { emoji: "🏐", label: "volleyball", keywords: ["sport", "ball"] },
    { emoji: "🏉", label: "rugby", keywords: ["sport", "ball"] },
    { emoji: "🥏", label: "flying disc", keywords: ["frisbee", "sport"] },
    { emoji: "🎱", label: "pool 8 ball", keywords: ["billiards", "game"] },
    { emoji: "🏓", label: "ping pong", keywords: ["table tennis", "sport"] },
    { emoji: "🏸", label: "badminton", keywords: ["sport", "shuttlecock"] },
    { emoji: "🥅", label: "goal net", keywords: ["sport", "score"] },
    { emoji: "⛳", label: "flag in hole", keywords: ["golf", "sport"] },
    { emoji: "🏹", label: "archery", keywords: ["bow", "sport"] },
    { emoji: "🎣", label: "fishing pole", keywords: ["fish", "sport", "catch"] },
    { emoji: "🤿", label: "diving mask", keywords: ["scuba", "snorkel"] },
    { emoji: "🎽", label: "running shirt", keywords: ["marathon", "sport"] },
    { emoji: "🎿", label: "skis", keywords: ["snow", "sport", "winter"] },
    { emoji: "🛷", label: "sled", keywords: ["snow", "winter"] },
    { emoji: "⛸️", label: "ice skate", keywords: ["skating", "winter", "sport"] },
    { emoji: "🥌", label: "curling stone", keywords: ["sport", "ice"] },
    { emoji: "🎯", label: "direct hit", keywords: ["bullseye", "target", "dart", "accuracy"] },
    { emoji: "🪀", label: "yo-yo", keywords: ["toy", "game"] },
    { emoji: "🪁", label: "kite", keywords: ["toy", "wind", "fly"] },
    { emoji: "🎮", label: "video game", keywords: ["controller", "gaming", "play"] },
    { emoji: "🕹️", label: "joystick", keywords: ["arcade", "game"] },
    { emoji: "🎲", label: "dice", keywords: ["game", "chance", "roll", "gamble"] },
    { emoji: "🧩", label: "puzzle piece", keywords: ["jigsaw", "solve", "fit"] },
    { emoji: "♟️", label: "chess pawn", keywords: ["chess", "strategy", "game"] },
    { emoji: "🃏", label: "joker", keywords: ["cards", "wild", "game"] },
    { emoji: "🀄", label: "mahjong", keywords: ["tiles", "game"] },
    { emoji: "🎴", label: "flower cards", keywords: ["cards", "game"] },

    // Arts / music
    { emoji: "🎨", label: "artist palette", keywords: ["art", "paint", "colors", "creative"] },
    { emoji: "🖌️", label: "paintbrush", keywords: ["brush", "paint", "art"] },
    { emoji: "🖍️", label: "crayon", keywords: ["draw", "color", "art"] },
    { emoji: "🧵", label: "thread spool", keywords: ["sewing", "craft"] },
    { emoji: "🎬", label: "clapper board", keywords: ["movie", "film", "action", "cinema"] },
    { emoji: "🎭", label: "performing arts", keywords: ["theater", "mask", "drama", "comedy", "tragedy"] },
    { emoji: "🎪", label: "circus tent", keywords: ["carnival", "show", "big top"] },
    { emoji: "🎤", label: "mic", keywords: ["sing", "karaoke", "speech"] },
    { emoji: "🎧", label: "earphones", keywords: ["music", "listen"] },
    { emoji: "🎼", label: "musical score", keywords: ["sheet music", "notes", "compose"] },
    { emoji: "🎹", label: "musical keyboard", keywords: ["piano", "keys", "music"] },
    { emoji: "🥁", label: "drum", keywords: ["percussion", "music", "beat"] },
    { emoji: "🎷", label: "saxophone", keywords: ["jazz", "music", "horn"] },
    { emoji: "🎺", label: "trumpet", keywords: ["brass", "music", "fanfare", "celebrate"] },
    { emoji: "🎸", label: "guitar", keywords: ["music", "rock", "acoustic"] },
    { emoji: "🪕", label: "banjo", keywords: ["music", "strings"] },
    { emoji: "🎻", label: "violin", keywords: ["music", "strings", "orchestra"] },
    { emoji: "🪗", label: "accordion", keywords: ["music", "squeeze box"] },

    // Money / charts
    { emoji: "💰", label: "money bag", keywords: ["finance", "wealth", "cash", "economy", "rich"] },
    { emoji: "💵", label: "dollar", keywords: ["cash", "bills", "usd", "money"] },
    { emoji: "💴", label: "yen", keywords: ["cash", "japan", "money"] },
    { emoji: "💶", label: "euro", keywords: ["cash", "europe", "money"] },
    { emoji: "💷", label: "pound", keywords: ["cash", "uk", "money"] },
    { emoji: "💸", label: "money with wings", keywords: ["spend", "loss", "cash"] },
    { emoji: "💳", label: "credit card", keywords: ["payment", "debit", "finance"] },
    { emoji: "💎", label: "diamond", keywords: ["jewel", "value", "gem"] },
    { emoji: "📉", label: "chart decreasing", keywords: ["decline", "loss", "graph", "data"] },
    { emoji: "📈", label: "chart increasing", keywords: ["growth", "profit", "graph", "data", "up"] },
    { emoji: "📊", label: "bar chart", keywords: ["data", "statistics", "graph", "analytics"] },
    { emoji: "🧾", label: "paper receipt", keywords: ["invoice", "proof"] },

    // Misc symbols / objects from original deck
    { emoji: "☂️", label: "umbrella", keywords: ["rain", "weather", "parasol"] },
    { emoji: "🎃", label: "jack-o-lantern", keywords: ["halloween", "pumpkin", "spooky"] },
    { emoji: "🧿", label: "nazar amulet", keywords: ["evil eye", "protection", "charm"] },
    { emoji: "🪬", label: "hamsa", keywords: ["protection", "hand", "charm"] },
    { emoji: "🔮", label: "crystal ball", keywords: ["fortune", "future", "mystic"] },
    { emoji: "🪄", label: "magic wand", keywords: ["spell", "wizard", "trick"] },
    { emoji: "🃏", label: "joker card", keywords: ["wild", "cards"] },
    { emoji: "🧿", label: "amulet", keywords: ["talisman", "protection"] },
    { emoji: "📿", label: "prayer beads", keywords: ["rosary", "religion"] },
    { emoji: "🧯", label: "extinguisher", keywords: ["fire safety"] },
    { emoji: "🚬", label: "cigarette", keywords: ["smoke", "tobacco"] },
    { emoji: "⚰️", label: "coffin", keywords: ["death", "funeral", "burial"] },
    { emoji: "⚱️", label: "funeral urn", keywords: ["ashes", "death", "memorial"] },
    { emoji: "🗿", label: "moai statue", keywords: ["stone face"] },
    { emoji: "🪧", label: "placard", keywords: ["sign", "protest", "picket"] },
    { emoji: "🚩", label: "triangular flag", keywords: ["marker", "golf", "alert"] },
    { emoji: "🏳️", label: "white flag", keywords: ["surrender", "truce", "peace"] },
    { emoji: "🏴", label: "black flag", keywords: ["pirate", "protest"] },
    { emoji: "🏁", label: "checkered flag", keywords: ["race", "finish", "win", "celebrate"] },
    { emoji: "🏳️‍🌈", label: "rainbow flag", keywords: ["pride", "lgbtq", "rainbow"] },
    { emoji: "🏴‍☠️", label: "pirate flag", keywords: ["jolly roger", "skull"] },

    // More everyday objects
    { emoji: "🛎️", label: "service bell", keywords: ["desk bell", "call"] },
    { emoji: "🪞", label: "looking glass", keywords: ["mirror"] },
    { emoji: "🪟", label: "window pane", keywords: ["glass"] },
    { emoji: "🛏️", label: "bed frame", keywords: ["sleep"] },
    { emoji: "🧸", label: "plush toy", keywords: ["teddy"] },
    { emoji: "🪆", label: "nesting dolls", keywords: ["matryoshka", "russia"] },
    { emoji: "🖼️", label: "framed picture", keywords: ["art", "portrait", "painting"] },
    { emoji: "🛒", label: "cart", keywords: ["shopping"] },
    { emoji: "🛍️", label: "shopping bags", keywords: ["retail", "purchase"] },
    { emoji: "🎀", label: "gift bow", keywords: ["ribbon"] },
    { emoji: "🎊", label: "party", keywords: ["celebrate"] },
    { emoji: "🎃", label: "pumpkin", keywords: ["halloween", "autumn"] },
    { emoji: "🪴", label: "potted plant", keywords: ["houseplant", "pot", "nature"] },
    { emoji: "🪵", label: "wood", keywords: ["log", "timber", "lumber"] },
    { emoji: "🪨", label: "rock", keywords: ["stone", "boulder"] },
    { emoji: "🕯️", label: "wax candle", keywords: ["flame"] },
    { emoji: "🪔", label: "diya lamp", keywords: ["oil lamp"] },
    { emoji: "🖊️", label: "ballpoint", keywords: ["write"] },
    { emoji: "🖋️", label: "fountain", keywords: ["pen"] },
    { emoji: "🖌️", label: "brush", keywords: ["paint"] },
    { emoji: "🖍️", label: "wax crayon", keywords: ["draw"] },
    { emoji: "📐", label: "triangular ruler", keywords: ["geometry", "measure", "math"] },
    { emoji: "📏", label: "straight ruler", keywords: ["measure", "length", "math"] },
    { emoji: "🧮", label: "abacus", keywords: ["count", "math", "calculate"] },
    { emoji: "📌", label: "thumbtack", keywords: ["pin"] },
    { emoji: "📍", label: "round pushpin", keywords: ["location"] },
    { emoji: "✂️", label: "shears", keywords: ["cut"] },
    { emoji: "🔏", label: "locked with pen", keywords: ["secure note"] },
    { emoji: "🔐", label: "locked key", keywords: ["secure"] },
    { emoji: "🔑", label: "key access", keywords: ["unlock"] },
  ];
