import type { DatabaseSync } from "node:sqlite";
import {
  DEFAULT_ZEN_ASK_QUESTION_PATIENCE_ENABLED,
  DEFAULT_ZEN_ASK_QUESTION_PATIENCE_MS,
  DEFAULT_ZEN_MESSAGE_FONT_MAX_PX,
  DEFAULT_ZEN_MESSAGE_FONT_MIN_PX,
  DEFAULT_ZEN_MOOD_SENSITIVITY,
  DEFAULT_ZEN_PERSONA_TRANSITION_CHOICE,
  DEFAULT_ZEN_WALLPAPER_BLURRED_EDGES_ENABLED,
  DEFAULT_ZEN_WALLPAPER_GRAYSCALE_ENABLED,
  DEFAULT_ZEN_WALLPAPER_OPACITY,
  DEFAULT_ZEN_WALLPAPER_STYLE_NOTES,
  DEFAULT_ZEN_WALLPAPER_TEXT_MASK_ENABLED,
} from "./settings.ts";

export const FACTORY_RESET_USER_DATA_TABLES = [
  "pairing_codes",
  "botcast_events",
  "botcast_messages",
  "botcast_episode_segments",
  "botcast_episodes",
  "botcast_shows",
  "coffee_poll_votes",
  "coffee_polls",
  "coffee_group_events",
  "coffee_group_seats",
  "coffee_presets",
  "coffee_cup_top_offs",
  "coffee_bot_social_state",
  "prism_mood_events",
  "prism_mood_state",
  "session_opinions",
  "bot_opinions",
  "bot_relationships",
  "developer_transcript_events",
  "conversation_exports",
  "conversation_sweep_batches",
  "zen_session_memories",
  "memory_summaries",
  "memories",
  "slate_continuity_context_briefs",
  "slate_continuity_source_indexes",
  "slate_continuity_jobs",
  "slate_continuity_concerns",
  "slate_continuity_knowledge",
  "slate_continuity_relationships",
  "slate_continuity_events",
  "slate_continuity_claims",
  "slate_continuity_aliases",
  "slate_continuity_entities",
  "slate_continuity_sources",
  "slate_continuity_generations",
  "slate_manuscript_exports",
  "slate_return_sessions",
  "slate_generation_receipts",
  "slate_project_chat_messages",
  "slate_living_summaries",
  "slate_title_suggestions",
  "slate_section_versions",
  "slate_manuscript_state",
  "slate_sections",
  "slate_revisions",
  "slate_versions",
  "slate_projects",
  "slate_series",
  "story_sessions",
  "images",
  "messages",
  "conversations",
  "coffee_groups",
  "bots",
] as const;

export function restoreFactoryDefaultsInDatabase(
  db: DatabaseSync,
  userId: string,
  nowIso = new Date().toISOString()
): void {
  db.exec("BEGIN IMMEDIATE TRANSACTION");
  try {
    for (const tableName of FACTORY_RESET_USER_DATA_TABLES) {
      db.prepare(`DELETE FROM ${tableName} WHERE user_id = ?`).run(userId);
    }

    const result = db
      .prepare(
        `
        UPDATE users
        SET
          theme = 'system',
          graphics_quality = 'high',
          preferred_provider = 'local',
          ephemeral_chat_provider_preferences = '{}',
          preferred_image_provider = 'local',
          provider_locked = 0,
          auto_memory = 1,
          auto_switch_model = 0,
          auto_fallback_chain = NULL,
          hidden_bot_model_ids = '[]',
          hidden_comfyui_workflow_ids = '[]',
          model_visibility_defaults_version = 0,
          preferred_local_model = NULL,
          preferred_online_model = NULL,
          lenient_local_fallback_model = NULL,
          lenient_local_image_fallback_model = NULL,
          secondary_ollama_host = NULL,
          experimental_dual_ollama_enabled = 0,
          experimental_all_model_effort_enabled = 0,
          coffee_experimental_table_angle_enabled = 0,
          psychic_mode_enabled = 0,
          comfyui_host = NULL,
          comfyui_workflows = '[]',
          preferred_local_image_model = NULL,
          preferred_openai_image_model = NULL,
          preferred_zen_wallpaper_local_image_model = NULL,
          preferred_zen_wallpaper_openai_image_model = NULL,
          zen_wallpaper_opacity = ?,
          zen_wallpaper_text_mask_enabled = ?,
          zen_wallpaper_grayscale_enabled = ?,
          zen_wallpaper_blurred_edges_enabled = ?,
          zen_wallpaper_style_notes = ?,
          zen_mood_sensitivity = ?,
          zen_message_font_min_px = ?,
          zen_message_font_max_px = ?,
          zen_ask_question_patience_enabled = ?,
          zen_ask_question_patience_ms = ?,
          zen_autonomy_enabled = 0,
          zen_persona_transition_choice = ?,
          composer_writing_assist = 1,
          fallback_model_message_stripe = 1,
          prism_default_bot_name = NULL,
          prism_default_bot_system_prompt = NULL,
          prism_default_bot_color = NULL,
          prism_default_bot_glyph = NULL,
          prism_default_bot_face_eyes_font = NULL,
          prism_default_bot_face_eye_character = NULL,
          prism_default_bot_face_eye_animation = NULL,
          prism_default_bot_face_mouth_font = NULL,
          prism_default_bot_face_mouth_character = NULL,
          prism_default_bot_face_mouth_animation = NULL,
          prism_default_bot_face_mouth_coffee_pucker = 0,
          prism_default_bot_face_font_weight = NULL,
          prism_default_bot_face_eye_scale = NULL,
          prism_default_bot_face_eye_offset_x = NULL,
          prism_default_bot_face_eye_offset_y = NULL,
          prism_default_bot_face_eye_rotation_deg = NULL,
          prism_default_bot_face_eye_count = 1,
          prism_default_bot_face_mouth_scale = NULL,
          prism_default_bot_face_mouth_offset_x = NULL,
          prism_default_bot_face_mouth_offset_y = NULL,
          prism_default_bot_face_mouth_rotation_deg = NULL,
          prism_default_bot_face_blink_bar = NULL,
          prism_default_bot_face_blink_scale = NULL,
          prism_default_bot_face_blink_offset_x = NULL,
          prism_default_bot_face_blink_offset_y = NULL,
          prism_default_bot_face_thinking_frames = NULL,
          prism_default_bot_audio_voice_profile = NULL,
          prism_default_bot_temperature = NULL,
          prism_default_bot_max_tokens = NULL,
          prism_default_bot_top_p = NULL,
          prism_default_bot_top_k = NULL,
          prism_default_bot_repetition_penalty = NULL,
          prism_default_llm_model = NULL,
          prism_image_tool_llm_model = NULL,
          dev_memories_enabled = 0,
          dev_memories_text = '',
          openai_key_ciphertext = NULL,
          openai_key_iv = NULL,
          openai_key_tag = NULL,
          anthropic_key_ciphertext = NULL,
          anthropic_key_iv = NULL,
          anthropic_key_tag = NULL,
          elevenlabs_key_ciphertext = NULL,
          elevenlabs_key_iv = NULL,
          elevenlabs_key_tag = NULL,
          brave_search_key_ciphertext = NULL,
          brave_search_key_iv = NULL,
          brave_search_key_tag = NULL,
          voice_mode = 'mute',
          voice_effects_enabled = 1,
          voice_volume = 1,
          english_voice_engine = 'builtin',
          default_system_voice_name = NULL,
          default_elevenlabs_voice_id = NULL,
          elevenlabs_voice_bank = '{}',
          elevenlabs_voice_model = NULL,
          elevenlabs_voice_collection_id = NULL,
          player_audio_voice_profile = NULL,
          player_name_pronunciation = '',
          last_active_at = ?
        WHERE id = ?
      `
      )
      .run(
        DEFAULT_ZEN_WALLPAPER_OPACITY,
        DEFAULT_ZEN_WALLPAPER_TEXT_MASK_ENABLED ? 1 : 0,
        DEFAULT_ZEN_WALLPAPER_GRAYSCALE_ENABLED ? 1 : 0,
        DEFAULT_ZEN_WALLPAPER_BLURRED_EDGES_ENABLED ? 1 : 0,
        DEFAULT_ZEN_WALLPAPER_STYLE_NOTES,
        DEFAULT_ZEN_MOOD_SENSITIVITY,
        DEFAULT_ZEN_MESSAGE_FONT_MIN_PX,
        DEFAULT_ZEN_MESSAGE_FONT_MAX_PX,
        DEFAULT_ZEN_ASK_QUESTION_PATIENCE_ENABLED ? 1 : 0,
        DEFAULT_ZEN_ASK_QUESTION_PATIENCE_MS,
        DEFAULT_ZEN_PERSONA_TRANSITION_CHOICE,
        nowIso,
        userId
      ) as {
      changes?: number | bigint;
    };

    if (Number(result.changes ?? 0) === 0) {
      throw new Error("User not found.");
    }

    db.exec("COMMIT");
  } catch (error) {
    db.exec("ROLLBACK");
    throw error;
  }
}
